import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokensPath = resolve(packageRoot, 'tokens.json');
const cssPath = resolve(packageRoot, 'styles.css');
const tsPath = resolve(packageRoot, 'src/tokens.ts');
const penTokensJsonPath = resolve(packageRoot, 'pen-tokens.json');
const pencilPenPath = resolve(packageRoot, 'tokens.pen');

const tokens = JSON.parse(await readFile(tokensPath, 'utf8'));

function getPathValue(path) {
  return path.split('.').reduce((value, key) => value?.[key], tokens);
}

function resolveReference(value) {
  if (typeof value !== 'string') return value;
  return value.replace(/\{([^}]+)\}/g, (_, path) => String(getPathValue(path)));
}

function resolveTree(value) {
  if (Array.isArray(value)) return value.map(resolveTree);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, resolveTree(child)]));
  }
  return resolveReference(value);
}

const resolved = resolveTree(tokens);

function clampByte(n) {
  return Math.max(0, Math.min(255, Math.round(Number(n))));
}

/** Pencil color fields prefer #RRGGBB or #RRGGBBAA (uppercase). */
function colorToPencil(value) {
  if (typeof value !== 'string') return '#000000';
  const v = value.trim();
  const rgba = v.match(
    /^rgba\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)$/i
  );
  if (rgba) {
    const r = clampByte(rgba[1]);
    const g = clampByte(rgba[2]);
    const b = clampByte(rgba[3]);
    const a = clampByte(Number(rgba[4]) * 255);
    const h = (n) => n.toString(16).toUpperCase().padStart(2, '0');
    return `#${h(r)}${h(g)}${h(b)}${h(a)}`;
  }
  const rgb = v.match(/^rgb\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*\)$/i);
  if (rgb) {
    const r = clampByte(rgb[1]);
    const g = clampByte(rgb[2]);
    const b = clampByte(rgb[3]);
    const h = (n) => n.toString(16).toUpperCase().padStart(2, '0');
    return `#${h(r)}${h(g)}${h(b)}`;
  }
  if (v.startsWith('#')) return v.toUpperCase();
  return v;
}

function buildPencilVariables() {
  const v = {};
  const color = (name, val) => {
    v[name] = { type: 'color', value: colorToPencil(String(val)) };
  };
  const str = (name, val) => {
    v[name] = { type: 'string', value: String(val) };
  };
  const num = (name, val) => {
    v[name] = { type: 'number', value: Number(val) };
  };

  const c = resolved.core.color;
  color('si-color-ink-950', c.ink['950']);
  color('si-color-ink-900', c.ink['900']);
  color('si-color-surface-800', c.surface['800']);
  color('si-color-slate-500', c.slate['500']);
  color('si-color-sage-500', c.sage['500']);
  color('si-color-cream-100', c.cream['100']);
  color('si-color-cream-200', c.cream['200']);
  color('si-color-paper-200', c.paper['200']);
  color('si-color-neutral-300', c.neutral['300']);
  color('si-color-neutral-200', c.neutral['200']);
  color('si-color-brand-500', c.brand['500']);
  color('si-color-brand-200', c.brand['200']);
  color('si-color-info-500', c.info['500']);
  color('si-color-info-200', c.info['200']);
  color('si-color-accent-500', c.accent['500']);
  color('si-color-accent-200', c.accent['200']);
  color('si-color-success-500', c.success['500']);
  color('si-color-danger-500', c.danger['500']);

  const s = resolved.semantic.color;
  color('si-color-bg-canvas', s.bg.canvas);
  color('si-color-bg-canvas-alt', s.bg.canvasAlt);
  color('si-color-bg-surface', s.bg.surface);
  color('si-color-bg-glass', s.bg.glass);
  color('si-color-text-primary', s.text.primary);
  color('si-color-text-secondary', s.text.secondary);
  color('si-color-text-muted', s.text.muted);
  color('si-color-border-strong', s.border.strong);
  color('si-color-border-subtle', s.border.subtle);
  color('si-color-focus', s.focus);
  color('si-color-chart-groceries', s.chart.groceries);
  color('si-color-chart-subscriptions', s.chart.subscriptions);
  color('si-color-chart-transport', s.chart.transport);
  color('si-color-chart-dining', s.chart.dining);
  color('si-color-chart-other', s.chart.other);

  str('si-font-body', resolved.semantic.font.body);
  str('si-font-ui', resolved.semantic.font.ui);
  str('si-font-display', resolved.semantic.font.display);

  for (const [key, val] of Object.entries(resolved.core.space)) {
    num(`si-space-${key}`, val);
  }
  for (const [key, val] of Object.entries(resolved.core.radius)) {
    num(`si-radius-${key}`, val);
  }

  str('si-shadow-soft', resolved.semantic.shadow.soft);
  str('si-shadow-hard', resolved.semantic.shadow.hard);

  return v;
}

const pencilVariables = buildPencilVariables();

const penTokensPayload = {
  description:
    'Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand; run npm run build in this package.',
  variables: pencilVariables
};

function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

const strokeSubtle = {
  align: 'inside',
  thickness: 1,
  fill: '$si-color-border-subtle'
};

/**
 * Full token specimen (colors, type, space, radius, UI sample) generated from `resolved`.
 * Product .pen files import this document for variables; open this file to review tokens in Pencil.
 */
function buildPencilSpecimenDocumentChildren() {
  const fonts = resolved.semantic.font;
  const sp = resolved.core.space;
  const rad = resolved.core.radius;

  const swatches = [
    ['Canvas', 'si-color-bg-canvas'],
    ['Surface', 'si-color-bg-surface'],
    ['Primary text', 'si-color-text-primary'],
    ['Muted text', 'si-color-text-muted'],
    ['Brand', 'si-color-brand-500'],
    ['Success', 'si-color-success-500'],
    ['Danger', 'si-color-danger-500'],
    ['Other', 'si-color-chart-other']
  ];

  const swatchCards = swatches.map(([label, key], i) => ({
    type: 'frame',
    id: `siSws${i}`,
    width: 104,
    height: 86,
    fill: '$si-color-bg-canvas-alt',
    cornerRadius: '$si-radius-md',
    stroke: strokeSubtle,
    layout: 'vertical',
    gap: 6,
    padding: 8,
    children: [
      {
        type: 'rectangle',
        id: `siSws${i}q`,
        width: 'fill_container',
        height: 28,
        cornerRadius: '$si-radius-sm',
        fill: `$${key}`
      },
      {
        type: 'text',
        id: `siSws${i}t`,
        fill: '$si-color-text-primary',
        content: label,
        fontFamily: 'Inter',
        fontSize: 11,
        fontWeight: '800',
        textGrowth: 'auto'
      }
    ]
  }));

  const swatchRows = chunk(swatchCards, 4).map((row, ri) => ({
    type: 'frame',
    id: `siSwRow${ri}`,
    width: 'fill_container',
    height: 94,
    layout: 'horizontal',
    gap: 12,
    alignItems: 'center',
    children: row
  }));

  const spaceBars = Object.entries(sp)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([k, w]) => ({
      type: 'frame',
      id: `siSpk${k}`,
      layout: 'vertical',
      gap: 4,
      width: Math.max(Number(w), 20),
      height: 58,
      alignItems: 'center',
      children: [
        {
          type: 'frame',
          id: `siSpb${k}`,
          width: Number(w),
          height: 36,
          fill: '$si-color-brand-500',
          cornerRadius: '$si-radius-sm'
        },
        {
          type: 'text',
          id: `siSpl${k}`,
          fill: '$si-color-text-muted',
          content: String(k),
          fontFamily: 'Inter',
          fontSize: 10,
          fontWeight: '600',
          textGrowth: 'auto'
        }
      ]
    }));

  const radiusTiles = Object.entries(rad).map(([k, r]) => ({
    type: 'frame',
    id: `siRdk${k}`,
    width: 76,
    height: 76,
    fill: '$si-color-bg-canvas-alt',
    cornerRadius: Number(r),
    stroke: strokeSubtle,
    layout: 'vertical',
    justifyContent: 'center',
    alignItems: 'center',
    children: [
      {
        type: 'text',
        id: `siRdl${k}`,
        fill: '$si-color-text-primary',
        content: k,
        fontFamily: 'Inter',
        fontSize: 11,
        fontWeight: '700',
        textGrowth: 'auto'
      }
    ]
  }));

  const chartStrip = ['groceries', 'subscriptions', 'transport', 'dining', 'other'].map((key, i) => ({
    type: 'frame',
    id: `siCh${i}`,
    width: 'fill_container',
    height: 'fill_container',
    fill: `$si-color-chart-${key}`,
    cornerRadius: '$si-radius-sm'
  }));

  return [
    {
      type: 'frame',
      id: 'siSpecRoot',
      name: 'Design tokens specimen',
      x: 32,
      y: 32,
      width: 960,
      height: 1320,
      fill: '$si-color-bg-canvas',
      cornerRadius: '$si-radius-xl',
      layout: 'vertical',
      gap: 18,
      padding: 24,
      children: [
        {
          type: 'frame',
          id: 'siSpecHdr',
          width: 'fill_container',
          fill: '$si-color-bg-surface',
          cornerRadius: '$si-radius-lg',
          stroke: strokeSubtle,
          layout: 'vertical',
          gap: 10,
          padding: 22,
          children: [
            {
              type: 'text',
              id: 'siSpecEyebrow',
              fill: '$si-color-brand-500',
              content: 'DESIGN TOKENS',
              fontFamily: 'Inter',
              fontSize: 12,
              fontWeight: '800',
              letterSpacing: 1.4,
              textGrowth: 'auto'
            },
            {
              type: 'text',
              id: 'siSpecTitle',
              fill: '$si-color-text-primary',
              content: 'Pencil token specimen',
              fontFamily: 'Inter',
              fontSize: 32,
              fontWeight: '800',
              textGrowth: 'auto'
            },
            {
              type: 'text',
              id: 'siSpecDesc',
              fill: '$si-color-text-secondary',
              textGrowth: 'fixed-width',
              width: 860,
              lineHeight: 1.3,
              fontFamily: 'Work Sans',
              fontSize: 15,
              fontWeight: 'normal',
              content:
                'Generated in tokens.pen from tokens.json. Import this document in product .pen files for variables; compare with web /tokens and the React Native Token Specimen screen.'
            }
          ]
        },
        {
          type: 'frame',
          id: 'siSpecColorSec',
          width: 'fill_container',
          fill: '$si-color-bg-surface',
          cornerRadius: '$si-radius-lg',
          stroke: strokeSubtle,
          layout: 'vertical',
          gap: 14,
          padding: 18,
          children: [
            {
              type: 'text',
              id: 'siSpecColorTitle',
              fill: '$si-color-text-primary',
              content: 'Color',
              fontFamily: 'Inter',
              fontSize: 20,
              fontWeight: '800',
              textGrowth: 'auto'
            },
            ...swatchRows
          ]
        },
        {
          type: 'frame',
          id: 'siSpecTypeSec',
          width: 'fill_container',
          fill: '$si-color-bg-surface',
          cornerRadius: '$si-radius-lg',
          stroke: strokeSubtle,
          layout: 'vertical',
          gap: 12,
          padding: 18,
          children: [
            {
              type: 'text',
              id: 'siSpecTypeTitle',
              fill: '$si-color-text-primary',
              content: 'Typography',
              fontFamily: 'Inter',
              fontSize: 20,
              fontWeight: '800',
              textGrowth: 'auto'
            },
            {
              type: 'text',
              id: 'siSpecDisplay',
              fill: '$si-color-text-primary',
              content: 'Display face',
              fontFamily: fonts.display,
              fontSize: 30,
              fontWeight: 'normal',
              textGrowth: 'auto'
            },
            {
              type: 'text',
              id: 'siSpecUi',
              fill: '$si-color-brand-500',
              content: 'UI LABEL AND CONTROLS',
              fontFamily: fonts.ui,
              fontSize: 13,
              fontWeight: '800',
              letterSpacing: 1.2,
              textGrowth: 'auto'
            },
            {
              type: 'text',
              id: 'siSpecBody',
              fill: '$si-color-text-secondary',
              content: 'Body copy with text.secondary for longer readable text.',
              fontFamily: fonts.body,
              fontSize: 15,
              fontWeight: 'normal',
              textGrowth: 'fixed-width',
              width: 860,
              lineHeight: 1.35
            }
          ]
        },
        {
          type: 'frame',
          id: 'siSpecSpaceSec',
          width: 'fill_container',
          fill: '$si-color-bg-surface',
          cornerRadius: '$si-radius-lg',
          stroke: strokeSubtle,
          layout: 'vertical',
          gap: 12,
          padding: 18,
          children: [
            {
              type: 'text',
              id: 'siSpecSpaceTitle',
              fill: '$si-color-text-primary',
              content: 'Space',
              fontFamily: 'Inter',
              fontSize: 20,
              fontWeight: '800',
              textGrowth: 'auto'
            },
            {
              type: 'frame',
              id: 'siSpecSpaceRow',
              width: 'fill_container',
              height: 68,
              layout: 'horizontal',
              gap: 12,
              alignItems: 'end',
              children: spaceBars
            }
          ]
        },
        {
          type: 'frame',
          id: 'siSpecRadSec',
          width: 'fill_container',
          fill: '$si-color-bg-surface',
          cornerRadius: '$si-radius-lg',
          stroke: strokeSubtle,
          layout: 'vertical',
          gap: 12,
          padding: 18,
          children: [
            {
              type: 'text',
              id: 'siSpecRadTitle',
              fill: '$si-color-text-primary',
              content: 'Radius',
              fontFamily: 'Inter',
              fontSize: 20,
              fontWeight: '800',
              textGrowth: 'auto'
            },
            {
              type: 'frame',
              id: 'siSpecRadRow',
              width: 'fill_container',
              height: 88,
              layout: 'horizontal',
              gap: 12,
              alignItems: 'center',
              children: radiusTiles
            }
          ]
        },
        {
          type: 'frame',
          id: 'siSpecDemo',
          width: 'fill_container',
          height: 132,
          fill: '$si-color-bg-surface',
          cornerRadius: '$si-radius-lg',
          stroke: strokeSubtle,
          gap: 14,
          padding: 18,
          layout: 'horizontal',
          alignItems: 'center',
          children: [
            {
              type: 'frame',
              id: 'siSpecMini',
              width: 'fill_container',
              height: 'fill_container',
              fill: '$si-color-bg-canvas-alt',
              cornerRadius: '$si-radius-lg',
              stroke: strokeSubtle,
              layout: 'vertical',
              gap: 8,
              padding: 14,
              children: [
                {
                  type: 'text',
                  id: 'siSpecMiniTitle',
                  fill: '$si-color-text-primary',
                  content: 'Budget card',
                  fontFamily: 'Inter',
                  fontSize: 17,
                  fontWeight: '800',
                  textGrowth: 'auto'
                },
                {
                  type: 'text',
                  id: 'siSpecMiniBody',
                  fill: '$si-color-text-secondary',
                  textGrowth: 'fixed-width',
                  width: 'fill_container',
                  content: 'Shared surface, text, radius, spacing, and chart colors.',
                  fontFamily: 'Work Sans',
                  fontSize: 13,
                  fontWeight: 'normal',
                  lineHeight: 1.35
                }
              ]
            },
            {
              type: 'frame',
              id: 'siSpecBtn',
              width: 176,
              height: 50,
              fill: '$si-color-brand-500',
              cornerRadius: '$si-radius-pill',
              layout: 'vertical',
              justifyContent: 'center',
              alignItems: 'center',
              children: [
                {
                  type: 'text',
                  id: 'siSpecBtnTx',
                  fill: '$si-color-bg-canvas',
                  content: 'Primary action',
                  fontFamily: 'Inter',
                  fontSize: 14,
                  fontWeight: '800',
                  textGrowth: 'auto'
                }
              ]
            },
            {
              type: 'frame',
              id: 'siSpecChart',
              width: 236,
              height: 50,
              layout: 'horizontal',
              gap: 6,
              children: chartStrip
            }
          ]
        }
      ]
    }
  ];
}

const pencilDocument = {
  version: '2.10',
  variables: pencilVariables,
  children: buildPencilSpecimenDocumentChildren()
};

function cssVar(name, value) {
  return `  --${name}: ${value};`;
}

function pxVar(name, value) {
  return cssVar(name, `${value}px`);
}

const css = `@import url('https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Inter:wght@400;500;600;700;800&family=Work+Sans:wght@400;500;600;700;800;900&display=swap');

:root {
  color-scheme: dark;

${[
  cssVar('si-color-ink-950', resolved.core.color.ink['950']),
  cssVar('si-color-ink-900', resolved.core.color.ink['900']),
  cssVar('si-color-surface-800', resolved.core.color.surface['800']),
  cssVar('si-color-slate-500', resolved.core.color.slate['500']),
  cssVar('si-color-sage-500', resolved.core.color.sage['500']),
  cssVar('si-color-cream-100', resolved.core.color.cream['100']),
  cssVar('si-color-cream-200', resolved.core.color.cream['200']),
  cssVar('si-color-paper-200', resolved.core.color.paper['200']),
  cssVar('si-color-neutral-300', resolved.core.color.neutral['300']),
  cssVar('si-color-neutral-200', resolved.core.color.neutral['200']),
  cssVar('si-color-brand-500', resolved.core.color.brand['500']),
  cssVar('si-color-brand-200', resolved.core.color.brand['200']),
  cssVar('si-color-info-500', resolved.core.color.info['500']),
  cssVar('si-color-info-200', resolved.core.color.info['200']),
  cssVar('si-color-accent-500', resolved.core.color.accent['500']),
  cssVar('si-color-accent-200', resolved.core.color.accent['200']),
  cssVar('si-color-success-500', resolved.core.color.success['500']),
  cssVar('si-color-danger-500', resolved.core.color.danger['500']),
  '',
  cssVar('si-color-bg-canvas', resolved.semantic.color.bg.canvas),
  cssVar('si-color-bg-canvas-alt', resolved.semantic.color.bg.canvasAlt),
  cssVar('si-color-bg-surface', resolved.semantic.color.bg.surface),
  cssVar('si-color-bg-glass', resolved.semantic.color.bg.glass),
  cssVar('si-color-text-primary', resolved.semantic.color.text.primary),
  cssVar('si-color-text-secondary', resolved.semantic.color.text.secondary),
  cssVar('si-color-text-muted', resolved.semantic.color.text.muted),
  cssVar('si-color-border-strong', resolved.semantic.color.border.strong),
  cssVar('si-color-border-subtle', resolved.semantic.color.border.subtle),
  cssVar('si-color-focus', resolved.semantic.color.focus),
  cssVar('si-color-chart-groceries', resolved.semantic.color.chart.groceries),
  cssVar('si-color-chart-subscriptions', resolved.semantic.color.chart.subscriptions),
  cssVar('si-color-chart-transport', resolved.semantic.color.chart.transport),
  cssVar('si-color-chart-dining', resolved.semantic.color.chart.dining),
  cssVar('si-color-chart-other', resolved.semantic.color.chart.other),
  '',
  cssVar('si-font-body', `'${resolved.semantic.font.body}', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`),
  cssVar('si-font-ui', `'${resolved.semantic.font.ui}', 'Work Sans', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`),
  cssVar('si-font-display', `'${resolved.semantic.font.display}', 'Work Sans', 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`),
  '',
  ...Object.entries(resolved.core.space).map(([key, value]) => pxVar(`si-space-${key}`, value)),
  '',
  ...Object.entries(resolved.core.radius).map(([key, value]) => pxVar(`si-radius-${key}`, value)),
  '',
  cssVar('si-shadow-soft', resolved.semantic.shadow.soft),
  cssVar('si-shadow-hard', resolved.semantic.shadow.hard)
].join('\n')}
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  font-family: var(--si-font-body);
  line-height: 1.5;
  font-weight: 400;
  background: var(--si-color-bg-canvas);
  color: var(--si-color-text-primary);
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
  background: var(--si-color-bg-canvas);
  color: var(--si-color-text-primary);
}

button,
input,
select,
textarea {
  font: inherit;
}

a {
  color: inherit;
  text-decoration: none;
}

#root {
  min-height: 100vh;
}
`;

const ts = `export const tokens = ${JSON.stringify(resolved, null, 2)} as const;

export const colors = {
  bgCanvas: tokens.semantic.color.bg.canvas,
  bgCanvasAlt: tokens.semantic.color.bg.canvasAlt,
  bgSurface: tokens.semantic.color.bg.surface,
  bgGlass: tokens.semantic.color.bg.glass,
  textPrimary: tokens.semantic.color.text.primary,
  textSecondary: tokens.semantic.color.text.secondary,
  textMuted: tokens.semantic.color.text.muted,
  borderStrong: tokens.semantic.color.border.strong,
  borderSubtle: tokens.semantic.color.border.subtle,
  focus: tokens.semantic.color.focus,
  brand: tokens.core.color.brand[500],
  sage: tokens.core.color.sage[500],
  info: tokens.semantic.color.status.info,
  success: tokens.semantic.color.status.success,
  danger: tokens.semantic.color.status.danger,
  chart: tokens.semantic.color.chart
} as const;

export const fonts = tokens.semantic.font;
export const space = tokens.core.space;
export const radius = tokens.core.radius;
export const platform = tokens.platform;
`;

await mkdir(dirname(tsPath), { recursive: true });
await writeFile(cssPath, css);
await writeFile(tsPath, ts);
await writeFile(penTokensJsonPath, `${JSON.stringify(penTokensPayload, null, 2)}\n`);
await writeFile(pencilPenPath, `${JSON.stringify(pencilDocument, null, 2)}\n`);
