version: v0.3.0

filters:
  - id: content_guard
    url: http://localhost:9090
    type: http

model_providers:
  - model: minmax/MiniMax-M2.7
    access_key: $PLANO_MINIMAX_API_KEY
    base_url: https://api.minimax.io/v1
    provider_interface: openai
    default: true

  - model: chatgpt/*

listeners:
  - type: model
    name: safe_model
    port: 12000
    timeout: 180s
    input_filters:
      - content_guard

tracing:
  random_sampling: 100
  opentracing_grpc_endpoint: http://localhost:4317
