#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# shellcheck source=./mode-env.sh
source "$ROOT_DIR/scripts/dev/mode-env.sh"
# shellcheck source=./port-cleanup.sh
source "$ROOT_DIR/scripts/dev/port-cleanup.sh"

expected_db_port_for_api_port() {
  case "$1" in
    4000) echo "6432" ;;
    4001) echo "7432" ;;
    *) echo "" ;;
  esac
}

EXPECTED_DB_PORT="$(expected_db_port_for_api_port "$TASKS_API_PORT")"
if [[ -n "$EXPECTED_DB_PORT" && "$POSTGRES_PORT" != "$EXPECTED_DB_PORT" ]]; then
  echo "Unsafe mode configuration: API port $TASKS_API_PORT expects DB port $EXPECTED_DB_PORT, got $POSTGRES_PORT." >&2
  echo "Check scripts/dev/mode-env.sh before starting the stack." >&2
  exit 1
fi

if ! command -v colima >/dev/null 2>&1; then
  echo "colima is required but not installed." >&2
  exit 1
fi

if ! command -v tilt >/dev/null 2>&1; then
  echo "tilt is required but not installed." >&2
  exit 1
fi

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker CLI is required but not installed." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
  echo "docker compose (plugin) or docker-compose is required but not installed." >&2
  exit 1
fi

if ! colima status >/dev/null 2>&1; then
  echo "Starting Colima..."
  colima start
fi

# Preflight: clear stale local listeners for this mode before Tilt boots.
cleanup_mode_ports

cat > "$ROOT_DIR/$TASKS_API_ENV_FILE" <<EOF
# Auto-generated by scripts/dev/up.sh for MODE=$MODE
PORT=$TASKS_API_PORT
DATABASE_URL="$DATABASE_URL"
CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS"
EOF

echo "Starting $MODE stack"
echo "  API: $TASKS_API_BASE_URL"
echo "  App: http://localhost:$TASKS_APP_PORT"
echo "  Postgres: localhost:$POSTGRES_PORT/$POSTGRES_DB"

cd "$ROOT_DIR"
exec tilt up --file infra/tilt/Tiltfile --port "$TILT_PORT"
