#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# shellcheck source=./mode-env.sh
source "$ROOT_DIR/scripts/dev/mode-env.sh"

if ! command -v colima >/dev/null 2>&1; then
  echo "colima is required but not installed." >&2
  exit 1
fi

if ! command -v tilt >/dev/null 2>&1; then
  echo "tilt is required but not installed." >&2
  exit 1
fi

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker CLI is required but not installed." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
  echo "docker compose (plugin) or docker-compose is required but not installed." >&2
  exit 1
fi

if ! colima status >/dev/null 2>&1; then
  echo "Starting Colima..."
  colima start
fi

# Preflight: clear stale local tasks-api watcher for this mode's port.
if pgrep -f "tsx watch src/server.ts" >/dev/null 2>&1; then
  if lsof -nP -iTCP:"$TASKS_API_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "Found stale tasks-api process on :$TASKS_API_PORT. Stopping it..."
    pkill -f "tsx watch src/server.ts" || true
    sleep 1
  fi
fi

cat > "$ROOT_DIR/$TASKS_API_ENV_FILE" <<EOF
# Auto-generated by scripts/dev/up.sh for MODE=$MODE
PORT=$TASKS_API_PORT
DATABASE_URL="$DATABASE_URL"
CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS"
EOF

echo "Starting $MODE stack"
echo "  API: $TASKS_API_BASE_URL"
echo "  App: http://localhost:$TASKS_APP_PORT"
echo "  Postgres: localhost:$POSTGRES_PORT/$POSTGRES_DB"

cd "$ROOT_DIR"
exec tilt up --file infra/tilt/Tiltfile --port "$TILT_PORT"
