- job_name: plano
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /stats/prometheus
  scheme: http
  static_configs:
    - targets:
        - 127.0.0.1:9901
      labels:
        environment: dev